name: Mac

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Pack
      run: npm pack:mac
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-build
        path: 'dist/*.dmg'
